In [11]:
#import the dependencies
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics
from sklearn.datasets import fetch_california_housing

In [1]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.1.2-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\users\sjyti\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\users\sjyti\anaconda3\lib\site-packages (from xgboost) (1.11.4)
Downloading xgboost-3.1.2-py3-none-win_amd64.whl (72.0 MB)
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/72.0 MB 487.6 kB/s eta 0:02:28
   ---------------------------------------- 0.2/72.0 MB 2.0 MB/s eta 0:00:37
    --------------------------------------- 1.1/72.0 MB 7.1 MB/s eta 0:00:10
   - -------------------------------------- 2.7/72.0 MB 13.5 MB/s eta 0:00:06
   - -------------------------------------- 2.9/72.0 MB 13.3 MB/s eta 0:00:06
   -- ------------------------------------- 4.7/72.0 MB 15.7 MB/s eta 0:00:05
   --- ------------------------------------ 6.1/72.0 MB 17.7 MB/s eta 0:00:04
   --- ------------------------------------ 7.1/72.0 MB 18.0 MB/s eta 0:00:04
   ---- ----------------------------------- 7.8/72.0 MB 17.8 MB/s eta 0:00:04
   ---- ----------------------------------- 8.6/72.0 MB 17.6 MB/s eta 0:00:04
   ----- ---------------------------------- 9.4/72.0 MB 17.6 MB/s eta 0:00:04
   ----- ---------------------------------- 10.2/72.0 MB 17.6 MB/s eta 0:00:04
   ------ --------------------------------- 11.0/72.0 MB 21.1 MB/s eta 0:00:03
   ------ --------------------------------- 11.8/72.0 MB 20.5 MB/s eta 0:00:03
   ------- -------------------------------- 12.7/72.0 MB 19.3 MB/s eta 0:00:04
   ------- -------------------------------- 13.5/72.0 MB 20.5 MB/s eta 0:00:03
   ------- -------------------------------- 14.3/72.0 MB 19.3 MB/s eta 0:00:03
   -------- ------------------------------- 14.9/72.0 MB 18.2 MB/s eta 0:00:04
   -------- ------------------------------- 15.4/72.0 MB 17.7 MB/s eta 0:00:04
   -------- ------------------------------- 15.9/72.0 MB 16.4 MB/s eta 0:00:04
   --------- ------------------------------ 16.3/72.0 MB 15.6 MB/s eta 0:00:04
   --------- ------------------------------ 16.7/72.0 MB 15.2 MB/s eta 0:00:04
   --------- ------------------------------ 17.1/72.0 MB 14.6 MB/s eta 0:00:04
   --------- ------------------------------ 17.5/72.0 MB 13.9 MB/s eta 0:00:04
   --------- ------------------------------ 18.0/72.0 MB 13.6 MB/s eta 0:00:04
   ---------- ----------------------------- 18.4/72.0 MB 13.4 MB/s eta 0:00:05
   ---------- ----------------------------- 18.8/72.0 MB 12.8 MB/s eta 0:00:05
   ---------- ----------------------------- 19.1/72.0 MB 12.6 MB/s eta 0:00:05
   ---------- ----------------------------- 19.5/72.0 MB 12.1 MB/s eta 0:00:05
   ---------- ----------------------------- 19.8/72.0 MB 11.7 MB/s eta 0:00:05
   ----------- ---------------------------- 20.0/72.0 MB 11.3 MB/s eta 0:00:05
   ----------- ---------------------------- 20.2/72.0 MB 10.9 MB/s eta 0:00:05
   ----------- ---------------------------- 20.4/72.0 MB 10.4 MB/s eta 0:00:05
   ----------- ---------------------------- 20.6/72.0 MB 10.1 MB/s eta 0:00:06
   ----------- ---------------------------- 20.7/72.0 MB 9.6 MB/s eta 0:00:06
   ----------- ---------------------------- 20.8/72.0 MB 9.4 MB/s eta 0:00:06
   ----------- ---------------------------- 21.0/72.0 MB 9.0 MB/s eta 0:00:06
   ----------- ---------------------------- 21.1/72.0 MB 8.7 MB/s eta 0:00:06
   ----------- ---------------------------- 21.3/72.0 MB 8.4 MB/s eta 0:00:07
   ----------- ---------------------------- 21.4/72.0 MB 8.2 MB/s eta 0:00:07
   ------------ --------------------------- 21.6/72.0 MB 8.0 MB/s eta 0:00:07
   ------------ --------------------------- 21.8/72.0 MB 7.7 MB/s eta 0:00:07
   ------------ --------------------------- 21.9/72.0 MB 7.5 MB/s eta 0:00:07
   ------------ --------------------------- 22.1/72.0 MB 7.4 MB/s eta 0:00:07
   ------------ --------------------------- 22.2/72.0 MB 7.2 MB/s eta 0:00:07
   ------------ --------------------------- 22.4/72.0 MB 6.9 MB/s eta 0:00:08
   ------------ --------------------------- 22.6/72.0 MB 6.7 MB/s eta 0:00:08
   ------------ --------------------------- 22.6/72.0 MB 6.6 MB/s eta 0:00:08
   ------------ --------------------------- 22.8/72.0 MB 6.5 MB/s eta 0:00:08
   ------------ --------------------------- 22.9/72.0 MB 6.3 MB/s eta 0:00:08
   ------------ --------------------------- 23.1/72.0 MB 6.2 MB/s eta 0:00:08
   ------------ --------------------------- 23.2/72.0 MB 6.0 MB/s eta 0:00:09
   ------------- -------------------------- 23.5/72.0 MB 5.9 MB/s eta 0:00:09
   ------------- -------------------------- 23.6/72.0 MB 5.8 MB/s eta 0:00:09
   ------------- -------------------------- 23.8/72.0 MB 5.6 MB/s eta 0:00:09
   ------------- -------------------------- 24.0/72.0 MB 5.6 MB/s eta 0:00:09
   ------------- -------------------------- 24.1/72.0 MB 5.5 MB/s eta 0:00:09
   ------------- -------------------------- 24.4/72.0 MB 5.4 MB/s eta 0:00:09
   ------------- -------------------------- 24.6/72.0 MB 5.3 MB/s eta 0:00:09
   ------------- -------------------------- 24.9/72.0 MB 5.2 MB/s eta 0:00:10
   ------------- -------------------------- 25.1/72.0 MB 5.1 MB/s eta 0:00:10
   -------------- ------------------------- 25.4/72.0 MB 5.1 MB/s eta 0:00:10
   -------------- ------------------------- 25.6/72.0 MB 5.0 MB/s eta 0:00:10
   -------------- ------------------------- 25.9/72.0 MB 5.0 MB/s eta 0:00:10
   -------------- ------------------------- 26.2/72.0 MB 4.9 MB/s eta 0:00:10
   -------------- ------------------------- 26.5/72.0 MB 4.9 MB/s eta 0:00:10
   -------------- ------------------------- 26.8/72.0 MB 4.9 MB/s eta 0:00:10
   --------------- ------------------------ 27.1/72.0 MB 4.8 MB/s eta 0:00:10
   --------------- ------------------------ 27.4/72.0 MB 4.8 MB/s eta 0:00:10
   --------------- ------------------------ 27.6/72.0 MB 4.7 MB/s eta 0:00:10
   --------------- ------------------------ 27.8/72.0 MB 4.7 MB/s eta 0:00:10
   --------------- ------------------------ 28.0/72.0 MB 4.6 MB/s eta 0:00:10
   --------------- ------------------------ 28.2/72.0 MB 4.6 MB/s eta 0:00:10
   --------------- ------------------------ 28.4/72.0 MB 4.5 MB/s eta 0:00:10
   --------------- ------------------------ 28.6/72.0 MB 4.5 MB/s eta 0:00:10
   --------------- ------------------------ 28.7/72.0 MB 4.5 MB/s eta 0:00:10
   --------------- ------------------------ 28.7/72.0 MB 4.3 MB/s eta 0:00:10
   ---------------- ----------------------- 28.9/72.0 MB 4.3 MB/s eta 0:00:11
   ---------------- ----------------------- 29.1/72.0 MB 4.3 MB/s eta 0:00:11
   ---------------- ----------------------- 29.3/72.0 MB 4.2 MB/s eta 0:00:11
   ---------------- ----------------------- 29.5/72.0 MB 4.2 MB/s eta 0:00:11
   ---------------- ----------------------- 29.6/72.0 MB 4.2 MB/s eta 0:00:11
   ---------------- ----------------------- 29.9/72.0 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 30.0/72.0 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 30.2/72.0 MB 4.1 MB/s eta 0:00:11
   ---------------- ----------------------- 30.3/72.0 MB 4.0 MB/s eta 0:00:11
   ---------------- ----------------------- 30.5/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 30.6/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 30.8/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 30.9/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 31.0/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 31.2/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 31.3/72.0 MB 4.0 MB/s eta 0:00:11
   ----------------- ---------------------- 31.3/72.0 MB 3.9 MB/s eta 0:00:11
   ----------------- ---------------------- 31.4/72.0 MB 3.9 MB/s eta 0:00:11
   ----------------- ---------------------- 31.5/72.0 MB 3.9 MB/s eta 0:00:11
   ----------------- ---------------------- 31.6/72.0 MB 3.8 MB/s eta 0:00:11
   ----------------- ---------------------- 31.7/72.0 MB 3.9 MB/s eta 0:00:11
   ----------------- ---------------------- 31.8/72.0 MB 3.8 MB/s eta 0:00:11
   ----------------- ---------------------- 31.9/72.0 MB 3.8 MB/s eta 0:00:11
   ----------------- ---------------------- 32.0/72.0 MB 3.8 MB/s eta 0:00:11
   ----------------- ---------------------- 32.1/72.0 MB 3.8 MB/s eta 0:00:11
   ----------------- ---------------------- 32.3/72.0 MB 3.7 MB/s eta 0:00:11
   ----------------- ---------------------- 32.3/72.0 MB 3.7 MB/s eta 0:00:11
   ------------------ --------------------- 32.4/72.0 MB 3.7 MB/s eta 0:00:11
   ------------------ --------------------- 32.5/72.0 MB 3.7 MB/s eta 0:00:11
   ------------------ --------------------- 32.6/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 32.7/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 32.8/72.0 MB 3.6 MB/s eta 0:00:12
   ------------------ --------------------- 32.9/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 33.0/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 33.1/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 33.2/72.0 MB 3.6 MB/s eta 0:00:11
   ------------------ --------------------- 33.3/72.0 MB 3.5 MB/s eta 0:00:11
   ------------------ --------------------- 33.4/72.0 MB 3.5 MB/s eta 0:00:12
   ------------------ --------------------- 33.4/72.0 MB 3.4 MB/s eta 0:00:12
   ------------------ --------------------- 33.5/72.0 MB 3.4 MB/s eta 0:00:12
   ------------------ --------------------- 33.5/72.0 MB 3.4 MB/s eta 0:00:12
   ------------------ --------------------- 33.5/72.0 MB 3.3 MB/s eta 0:00:12
   ------------------ --------------------- 33.6/72.0 MB 3.3 MB/s eta 0:00:12
   ------------------ --------------------- 33.7/72.0 MB 3.3 MB/s eta 0:00:12
   ------------------ --------------------- 33.7/72.0 MB 3.2 MB/s eta 0:00:12
   ------------------ --------------------- 33.8/72.0 MB 3.2 MB/s eta 0:00:12
   ------------------ --------------------- 33.9/72.0 MB 3.2 MB/s eta 0:00:12
   ------------------ --------------------- 34.0/72.0 MB 3.2 MB/s eta 0:00:12
   ------------------ --------------------- 34.1/72.0 MB 3.1 MB/s eta 0:00:13
   ------------------ --------------------- 34.1/72.0 MB 3.1 MB/s eta 0:00:13
   ------------------- -------------------- 34.2/72.0 MB 3.1 MB/s eta 0:00:13
   ------------------- -------------------- 34.3/72.0 MB 3.1 MB/s eta 0:00:13
   ------------------- -------------------- 34.4/72.0 MB 3.1 MB/s eta 0:00:13
   ------------------- -------------------- 34.5/72.0 MB 3.0 MB/s eta 0:00:13
   ------------------- -------------------- 34.6/72.0 MB 3.0 MB/s eta 0:00:13
   ------------------- -------------------- 34.7/72.0 MB 3.0 MB/s eta 0:00:13
   ------------------- -------------------- 34.7/72.0 MB 3.0 MB/s eta 0:00:13
   ------------------- -------------------- 34.8/72.0 MB 2.9 MB/s eta 0:00:13
   ------------------- -------------------- 35.0/72.0 MB 2.9 MB/s eta 0:00:13
   ------------------- -------------------- 35.1/72.0 MB 2.9 MB/s eta 0:00:13
   ------------------- -------------------- 35.2/72.0 MB 2.9 MB/s eta 0:00:13
   ------------------- -------------------- 35.3/72.0 MB 2.9 MB/s eta 0:00:13
   ------------------- -------------------- 35.4/72.0 MB 2.8 MB/s eta 0:00:13
   ------------------- -------------------- 35.6/72.0 MB 2.8 MB/s eta 0:00:13
   ------------------- -------------------- 35.7/72.0 MB 2.8 MB/s eta 0:00:13
   ------------------- -------------------- 35.8/72.0 MB 2.8 MB/s eta 0:00:14
   ------------------- -------------------- 36.0/72.0 MB 2.8 MB/s eta 0:00:14
   -------------------- ------------------- 36.1/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 36.2/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 36.4/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 36.6/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 36.7/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 36.9/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 37.0/72.0 MB 2.7 MB/s eta 0:00:14
   -------------------- ------------------- 37.3/72.0 MB 2.6 MB/s eta 0:00:14
   -------------------- ------------------- 37.4/72.0 MB 2.6 MB/s eta 0:00:14
   -------------------- ------------------- 37.5/72.0 MB 2.6 MB/s eta 0:00:14
   -------------------- ------------------- 37.6/72.0 MB 2.6 MB/s eta 0:00:14
   -------------------- ------------------- 37.8/72.0 MB 2.6 MB/s eta 0:00:14
   --------------------- ------------------ 37.9/72.0 MB 2.6 MB/s eta 0:00:14
   --------------------- ------------------ 38.0/72.0 MB 2.6 MB/s eta 0:00:14
   --------------------- ------------------ 38.2/72.0 MB 2.6 MB/s eta 0:00:14
   --------------------- ------------------ 38.3/72.0 MB 2.5 MB/s eta 0:00:14
   --------------------- ------------------ 38.4/72.0 MB 2.5 MB/s eta 0:00:14
   --------------------- ------------------ 38.6/72.0 MB 2.5 MB/s eta 0:00:14
   --------------------- ------------------ 38.7/72.0 MB 2.5 MB/s eta 0:00:14
   --------------------- ------------------ 38.9/72.0 MB 2.5 MB/s eta 0:00:14
   --------------------- ------------------ 39.1/72.0 MB 2.6 MB/s eta 0:00:13
   --------------------- ------------------ 39.2/72.0 MB 2.5 MB/s eta 0:00:13
   --------------------- ------------------ 39.4/72.0 MB 2.5 MB/s eta 0:00:13
   ---------------------- ----------------- 39.6/72.0 MB 2.5 MB/s eta 0:00:13
   ---------------------- ----------------- 39.8/72.0 MB 2.5 MB/s eta 0:00:13
   ---------------------- ----------------- 40.0/72.0 MB 2.5 MB/s eta 0:00:13
   ---------------------- ----------------- 40.2/72.0 MB 2.6 MB/s eta 0:00:13
   ---------------------- ----------------- 40.4/72.0 MB 2.6 MB/s eta 0:00:13
   ---------------------- ----------------- 40.6/72.0 MB 2.6 MB/s eta 0:00:13
   ---------------------- ----------------- 40.8/72.0 MB 2.6 MB/s eta 0:00:13
   ---------------------- ----------------- 41.0/72.0 MB 2.6 MB/s eta 0:00:12
   ---------------------- ----------------- 41.3/72.0 MB 2.6 MB/s eta 0:00:12
   ----------------------- ---------------- 41.5/72.0 MB 2.7 MB/s eta 0:00:12
   ----------------------- ---------------- 41.7/72.0 MB 2.7 MB/s eta 0:00:12
   ----------------------- ---------------- 41.9/72.0 MB 2.8 MB/s eta 0:00:11
   ----------------------- ---------------- 42.2/72.0 MB 2.8 MB/s eta 0:00:11
   ----------------------- ---------------- 42.4/72.0 MB 2.8 MB/s eta 0:00:11
   ----------------------- ---------------- 42.7/72.0 MB 2.9 MB/s eta 0:00:11
   ----------------------- ---------------- 43.0/72.0 MB 3.0 MB/s eta 0:00:10
   ------------------------ --------------- 43.2/72.0 MB 3.1 MB/s eta 0:00:10
   ------------------------ --------------- 43.5/72.0 MB 3.1 MB/s eta 0:00:10
   ------------------------ --------------- 43.7/72.0 MB 3.2 MB/s eta 0:00:09
   ------------------------ --------------- 44.0/72.0 MB 3.4 MB/s eta 0:00:09
   ------------------------ --------------- 44.2/72.0 MB 3.5 MB/s eta 0:00:08
   ------------------------ --------------- 44.4/72.0 MB 3.6 MB/s eta 0:00:08
   ------------------------ --------------- 44.5/72.0 MB 3.7 MB/s eta 0:00:08
   ------------------------ --------------- 44.8/72.0 MB 3.7 MB/s eta 0:00:08
   ------------------------ --------------- 45.0/72.0 MB 3.8 MB/s eta 0:00:08
   ------------------------- -------------- 45.2/72.0 MB 3.9 MB/s eta 0:00:07
   ------------------------- -------------- 45.4/72.0 MB 3.9 MB/s eta 0:00:07
   ------------------------- -------------- 45.6/72.0 MB 4.0 MB/s eta 0:00:07
   ------------------------- -------------- 45.8/72.0 MB 4.0 MB/s eta 0:00:07
   ------------------------- -------------- 46.0/72.0 MB 4.1 MB/s eta 0:00:07
   ------------------------- -------------- 46.2/72.0 MB 4.1 MB/s eta 0:00:07
   ------------------------- -------------- 46.4/72.0 MB 4.2 MB/s eta 0:00:07
   ------------------------- -------------- 46.6/72.0 MB 4.2 MB/s eta 0:00:07
   ------------------------- -------------- 46.7/72.0 MB 4.2 MB/s eta 0:00:07
   -------------------------- ------------- 46.9/72.0 MB 4.2 MB/s eta 0:00:07
   -------------------------- ------------- 47.1/72.0 MB 4.2 MB/s eta 0:00:06
   -------------------------- ------------- 47.2/72.0 MB 4.2 MB/s eta 0:00:06
   -------------------------- ------------- 47.4/72.0 MB 4.2 MB/s eta 0:00:06
   -------------------------- ------------- 47.6/72.0 MB 4.2 MB/s eta 0:00:06
   -------------------------- ------------- 47.8/72.0 MB 4.2 MB/s eta 0:00:06
   -------------------------- ------------- 48.0/72.0 MB 4.3 MB/s eta 0:00:06
   -------------------------- ------------- 48.2/72.0 MB 4.3 MB/s eta 0:00:06
   -------------------------- ------------- 48.4/72.0 MB 4.3 MB/s eta 0:00:06
   -------------------------- ------------- 48.6/72.0 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 48.8/72.0 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 49.0/72.0 MB 4.5 MB/s eta 0:00:06
   --------------------------- ------------ 49.2/72.0 MB 4.5 MB/s eta 0:00:06
   --------------------------- ------------ 49.5/72.0 MB 4.5 MB/s eta 0:00:05
   --------------------------- ------------ 49.6/72.0 MB 4.5 MB/s eta 0:00:05
   --------------------------- ------------ 49.7/72.0 MB 4.5 MB/s eta 0:00:05
   --------------------------- ------------ 49.8/72.0 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 49.9/72.0 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 50.0/72.0 MB 4.4 MB/s eta 0:00:06
   --------------------------- ------------ 50.1/72.0 MB 4.3 MB/s eta 0:00:06
   --------------------------- ------------ 50.3/72.0 MB 4.3 MB/s eta 0:00:06
   --------------------------- ------------ 50.3/72.0 MB 4.3 MB/s eta 0:00:06
   ---------------------------- ----------- 50.4/72.0 MB 4.2 MB/s eta 0:00:06
   ---------------------------- ----------- 50.5/72.0 MB 4.1 MB/s eta 0:00:06
   ---------------------------- ----------- 50.6/72.0 MB 4.1 MB/s eta 0:00:06
   ---------------------------- ----------- 50.7/72.0 MB 4.0 MB/s eta 0:00:06
   ---------------------------- ----------- 50.8/72.0 MB 4.0 MB/s eta 0:00:06
   ---------------------------- ----------- 50.9/72.0 MB 3.9 MB/s eta 0:00:06
   ---------------------------- ----------- 51.0/72.0 MB 3.9 MB/s eta 0:00:06
   ---------------------------- ----------- 51.1/72.0 MB 3.9 MB/s eta 0:00:06
   ---------------------------- ----------- 51.2/72.0 MB 3.9 MB/s eta 0:00:06
   ---------------------------- ----------- 51.3/72.0 MB 3.9 MB/s eta 0:00:06
   ---------------------------- ----------- 51.4/72.0 MB 3.8 MB/s eta 0:00:06
   ---------------------------- ----------- 51.5/72.0 MB 3.8 MB/s eta 0:00:06
   ---------------------------- ----------- 51.6/72.0 MB 3.7 MB/s eta 0:00:06
   ---------------------------- ----------- 51.8/72.0 MB 3.7 MB/s eta 0:00:06
   ---------------------------- ----------- 51.9/72.0 MB 3.7 MB/s eta 0:00:06
   ---------------------------- ----------- 52.0/72.0 MB 3.7 MB/s eta 0:00:06
   ---------------------------- ----------- 52.2/72.0 MB 3.7 MB/s eta 0:00:06
   ----------------------------- ---------- 52.3/72.0 MB 3.6 MB/s eta 0:00:06
   ----------------------------- ---------- 52.5/72.0 MB 3.6 MB/s eta 0:00:06
   ----------------------------- ---------- 52.6/72.0 MB 3.6 MB/s eta 0:00:06
   ----------------------------- ---------- 52.7/72.0 MB 3.5 MB/s eta 0:00:06
   ----------------------------- ---------- 52.9/72.0 MB 3.5 MB/s eta 0:00:06
   ----------------------------- ---------- 53.0/72.0 MB 3.5 MB/s eta 0:00:06
   ----------------------------- ---------- 53.2/72.0 MB 3.5 MB/s eta 0:00:06
   ----------------------------- ---------- 53.3/72.0 MB 3.4 MB/s eta 0:00:06
   ----------------------------- ---------- 53.4/72.0 MB 3.4 MB/s eta 0:00:06

In [12]:
house_price_dataset = fetch_california_housing()

In [14]:
print(house_price_dataset)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 20640\n\n    :Number of Attributes: 8 numeric, predictive attributes and the target\n\n    :Attribute Information:\n        - MedInc        median income in block group\n        - HouseAge      median house age in block group\n        - AveRooms      average number of rooms per household\n        - AveBedrms     average number of bedrooms per household\n        - Population    block group population\n        - AveOccup      average number of household members\n        - Latitude      block group latitude\n        - Longitude     block group longitude\n\n    :Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. topic:: References\n\n    - Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n      Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [18]:
# loading the dataset a pandas dataframe
house_price_dataframe=pd.DataFrame(house_price_dataset.data,columns =house_price_dataset.feature_names)

In [16]:
#print first 5 rows of our dataframe 
house_price_dataframe.head()

        0     1         2         3       4         5      6       7
0  8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1  8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2  7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3  5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4  3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25

In [19]:
#add the target(price) column to the DataFrame
house_price_dataframe['price']=house_price_dataset.target

In [20]:
house_price_dataframe.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,price
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [21]:
#checking the number of rows and columns in the dataframe 
house_price_dataframe.shape

(20640, 9)